using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ETS2_Assist_GUI
{
    public partial class MainForm
    {
        // ================================================================
        // ГЕНЕРАЦИЯ HTML-ПЛЕЕРА ДЛЯ КОМПАКТНОГО ТРЕКА
        // ================================================================


        private string GenerateTrailHtml(string compactData, JObject? meta, JObject? mapData)
        {
            string escapedData = JsonConvert.ToString(compactData);
            string metaJson = meta != null ? meta.ToString(Formatting.None) : "{}";
            string mapJson = mapData != null ? mapData.ToString(Formatting.None) : "{}";

            var sb = new StringBuilder();
            sb.AppendLine("<!DOCTYPE html>");
            sb.AppendLine("<html>");
            sb.AppendLine("<head>");
            sb.AppendLine("    <meta charset=\"utf-8\"/>");
            sb.AppendLine("    <title>ETS2 Trail Viewer</title>");
            sb.AppendLine("    <style>");
            sb.AppendLine("        body { margin:0; background:#0a0c10; color:#e0e0e0; font-family:'Segoe UI',sans-serif; overflow:hidden; }");
            sb.AppendLine("        #mapCanvas { display:block; width:100vw; height:calc(100vh - 150px); background:#111; cursor:grab; }");
            sb.AppendLine("        #controls { position:fixed; bottom:0; left:0; right:0; background:#1a1f26; padding:8px 15px; border-top:1px solid #333; display:flex; flex-direction:column; gap:6px; }");
            sb.AppendLine("        #controlsTop { display:flex; align-items:center; gap:8px; flex-wrap:wrap; }");
            sb.AppendLine("        #controlsBottom { display:flex; align-items:center; gap:10px; }");
            sb.AppendLine("        #controls button, #controls input { background:#2a3545; border:1px solid #4a5a6a; color:#d0def0; border-radius:4px; padding:4px 10px; font-size:13px; cursor:pointer; }");
            sb.AppendLine("        #controls button:hover { background:#3a4a5a; }");
            sb.AppendLine("        #timeSlider { flex:1; min-width:200px; }");
            sb.AppendLine("        #speedLabel { font-size:13px; color:#8fa0b9; }");
            sb.AppendLine("        #checkboxFollow { margin-left:8px; }");
            sb.AppendLine("        #timeDisplay { font-size:13px; color:#aabbcc; min-width:120px; font-family:monospace; }");
            sb.AppendLine("        #stepInput { width:60px; background:#0c1016; border:1px solid #2f3845; border-radius:4px; padding:3px 6px; color:#e0e9f5; font-size:13px; font-family:monospace; }");
            sb.AppendLine("        #info { position:absolute; top:10px; right:10px; background:rgba(0,0,0,0.7); padding:6px 12px; border-radius:6px; font-size:12px; color:#ccc; }");
            sb.AppendLine("        #dataPanel { position:absolute; bottom:160px; left:20px; background:rgba(0,0,0,0.7); padding:8px 14px; border-radius:6px; font-size:11px; color:#aabbcc; border:1px solid #333; backdrop-filter:blur(4px); pointer-events:none; }");
            sb.AppendLine("        #titlePanel { position:absolute; top:10px; left:10px; background:rgba(0,0,0,0.7); padding:6px 14px; border-radius:6px; font-size:12px; color:#e0e0e0; border:1px solid #444; backdrop-filter:blur(4px); pointer-events:none; }");
            sb.AppendLine("        #cursorCoords { position:absolute; bottom:160px; right:20px; background:rgba(0,0,0,0.7); padding:2px 8px; border-radius:4px; font-size:10px; color:#8fa0b9; pointer-events:none; }");
            sb.AppendLine("        #measureTool { position:absolute; top:60px; left:10px; background:rgba(0,0,0,0.7); padding:4px 10px; border-radius:4px; font-size:11px; color:#ffc857; border:1px solid #ffc85744; display:none; pointer-events:none; }");
            sb.AppendLine("        #measureTool.active { display:block; }");
            sb.AppendLine("        .note-btn { background:#2a3545; border:1px solid #4a5a6a; color:#d0def0; border-radius:4px; padding:2px 6px; font-size:11px; cursor:pointer; }");
            sb.AppendLine("        .note-btn:hover { background:#3a4a5a; }");
            sb.AppendLine("        /* Индикатор pitch/roll */");
            sb.AppendLine("        #prIndicator { position:absolute; bottom:160px; left:50%; transform:translateX(-50%); background:rgba(0,0,0,0.7); padding:4px 12px; border-radius:6px; font-size:11px; color:#aabbcc; border:1px solid #444; backdrop-filter:blur(4px); display:flex; gap:16px; pointer-events:none; }");
            sb.AppendLine("        #prIndicator .pr-item { display:flex; align-items:center; gap:6px; }");
            sb.AppendLine("        #prIndicator .pr-bar { width:60px; height:6px; background:#2a3545; border-radius:3px; overflow:hidden; }");
            sb.AppendLine("        #prIndicator .pr-fill { height:100%; border-radius:3px; transition:width 0.05s; }");
            sb.AppendLine("        #prIndicator .pr-label { color:#8fa0b9; font-size:10px; min-width:30px; text-align:right; }");
            sb.AppendLine("    </style>");
            sb.AppendLine("</head>");
            sb.AppendLine("<body>");
            sb.AppendLine("<div id=\"info\">Просмотр трека</div>");
            sb.AppendLine("<div id=\"titlePanel\"></div>");
            sb.AppendLine("<div id=\"dataPanel\">⛽ -- л &nbsp;|&nbsp; 🛠️ --%</div>");
            sb.AppendLine("<div id=\"cursorCoords\"></div>");
            sb.AppendLine("<div id=\"measureTool\">📏 Расстояние: <span id=\"measureDist\">0.0</span> м</div>");
            sb.AppendLine("<div id=\"prIndicator\">");
            sb.AppendLine("    <div class=\"pr-item\">");
            sb.AppendLine("        <span>Pitch</span>");
            sb.AppendLine("        <div class=\"pr-bar\"><div class=\"pr-fill\" id=\"pitchFill\" style=\"width:50%;background:#ff6b6b;\"></div></div>");
            sb.AppendLine("        <span class=\"pr-label\" id=\"pitchLabel\">0</span>");
            sb.AppendLine("    </div>");
            sb.AppendLine("    <div class=\"pr-item\">");
            sb.AppendLine("        <span>Roll</span>");
            sb.AppendLine("        <div class=\"pr-bar\"><div class=\"pr-fill\" id=\"rollFill\" style=\"width:50%;background:#4ecdc4;\"></div></div>");
            sb.AppendLine("        <span class=\"pr-label\" id=\"rollLabel\">0</span>");
            sb.AppendLine("    </div>");
            sb.AppendLine("</div>");
            sb.AppendLine("<canvas id=\"mapCanvas\"></canvas>");
            sb.AppendLine("<div id=\"controls\">");
            sb.AppendLine("    <div id=\"controlsTop\">");
            sb.AppendLine("        <button id=\"playBtn\">▶</button>");
            sb.AppendLine("        <button id=\"beginBtn\">⏮</button>");
            sb.AppendLine("        <button id=\"endBtn\">⏭</button>");
            sb.AppendLine("        <button id=\"stepBackBtn\">◀</button>");
            sb.AppendLine("        <button id=\"stepForwardBtn\">▶</button>");
            sb.AppendLine("        <button id=\"prevEventBtn\">⏪</button>");
            sb.AppendLine("        <button id=\"nextEventBtn\">⏩</button>");
            sb.AppendLine("        <span style=\"color:#8fa0b9;font-size:13px;\">Шаг:</span>");
            sb.AppendLine("        <input type=\"number\" id=\"stepInput\" value=\"1\" min=\"0.5\" max=\"600\" step=\"0.5\">");
            sb.AppendLine("        <span style=\"color:#8fa0b9;font-size:12px;\">с</span>");
            sb.AppendLine("        <span id=\"speedLabel\">1×</span>");
            sb.AppendLine("        <button id=\"speedDownBtn\">−</button>");
            sb.AppendLine("        <button id=\"speedUpBtn\">+</button>");
            sb.AppendLine("        <label style=\"color:#8fa0b9;font-size:13px;\"><input type=\"checkbox\" id=\"followCheck\" checked> Следить</label>");
            sb.AppendLine("        <label style=\"color:#8fa0b9;font-size:13px;\"><input type=\"checkbox\" id=\"interpolateCheck\" checked> Интерполяция</label>");
            sb.AppendLine("    </div>");
            sb.AppendLine("    <div id=\"controlsBottom\">");
            sb.AppendLine("        <input type=\"range\" id=\"timeSlider\" min=\"0\" max=\"1000\" value=\"0\" style=\"flex:1;\">");
            sb.AppendLine("        <span id=\"timeDisplay\">00:00:00.000</span>");
            sb.AppendLine("    </div>");
            sb.AppendLine("</div>");
            sb.AppendLine("<script>");
            sb.AppendLine($"const compactData = {escapedData};");
            sb.AppendLine($"const metaData = {metaJson};");
            sb.AppendLine($"const mapData = {mapJson};");
            sb.AppendLine("");
            sb.AppendLine("// ================================================================");
            sb.AppendLine("// ПАРСЕР КОМПАКТНОГО ТРЕКА");
            sb.AppendLine("// ================================================================");
            sb.AppendLine("function parseTrail(data) {");
            sb.AppendLine("    const lines = data.split('\\n').filter(l => l.trim() !== '');");
            sb.AppendLine("    if (lines.length === 0) return { meta: {}, trail: [], dataPoints: [], events: [] };");
            sb.AppendLine("    let meta = {};");
            sb.AppendLine("    try { meta = JSON.parse(lines[0]); } catch(e) { meta = {}; }");
            sb.AppendLine("    const trail = [];");
            sb.AppendLine("    const dataPoints = [];");
            sb.AppendLine("    const events = [];");
            sb.AppendLine("    const eventTypes = meta.eventTypes || {};");
            sb.AppendLine("    const typeNames = Object.fromEntries(Object.entries(eventTypes).map(([k,v]) => [v,k]));");
            sb.AppendLine("    for (let i=1; i<lines.length; i++) {");
            sb.AppendLine("        const parts = lines[i].split(';');");
            sb.AppendLine("        if (parts.length === 0) continue;");
            sb.AppendLine("        const type = parts[0];");
            sb.AppendLine("        if (type === 'D') {");
            sb.AppendLine("            dataPoints.push({ t: parseFloat(parts[1]), x: parseFloat(parts[2]), z: parseFloat(parts[3]), heading: parseFloat(parts[4]), fuel: parseFloat(parts[5]), damage: parseFloat(parts[6]), pitch: parseFloat(parts[7] || 0), roll: parseFloat(parts[8] || 0) });");
            sb.AppendLine("        } else if (type === 'E') {");
            sb.AppendLine("            const eType = typeNames[parseInt(parts[4])] || 'unknown';");
            sb.AppendLine("            events.push({ t: parseFloat(parts[1]), x: parseFloat(parts[2]), z: parseFloat(parts[3]), type: eType, label: parts[5], color: parts[6], subtext: parts[7] });");
            sb.AppendLine("        } else {");
            sb.AppendLine("            trail.push({ t: parseFloat(parts[0]), x: parseFloat(parts[1]), z: parseFloat(parts[2]), heading: parseFloat(parts[3]), speed: parseFloat(parts[4]) });");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("    return { meta, trail, dataPoints, events };");
            sb.AppendLine("}");
            sb.AppendLine("");
            sb.AppendLine("const parsed = parseTrail(compactData);");
            sb.AppendLine("const trailPoints = parsed.trail;");
            sb.AppendLine("const dataPoints = parsed.dataPoints;");
            sb.AppendLine("const events = parsed.events;");
            sb.AppendLine("const meta = parsed.meta;");
            sb.AppendLine("");
            sb.AppendLine("// Данные карты (города, дороги)");
            sb.AppendLine("const cities = mapData?.cities || [];");
            sb.AppendLine("const roads = mapData?.roads || [];");
            sb.AppendLine("");
            sb.AppendLine("// Времена точек");
            sb.AppendLine("const times = trailPoints.map(p => p.t);");
            sb.AppendLine("const totalDuration = times.length > 0 ? times[times.length-1] : 0;");
            sb.AppendLine("");
            sb.AppendLine("// Заголовок");
            sb.AppendLine("const title = meta.title || '';");
            sb.AppendLine("const desc = meta.description || '';");
            sb.AppendLine("document.getElementById('titlePanel').innerHTML = title + (desc ? '<br><span style=\"font-size:10px;color:#888;\">'+desc+'</span>' : '');");
            sb.AppendLine("");
            sb.AppendLine("const canvas = document.getElementById('mapCanvas');");
            sb.AppendLine("const ctx = canvas.getContext('2d');");
            sb.AppendLine("let W, H;");
            sb.AppendLine("function resize() { W = canvas.width = window.innerWidth; H = canvas.height = window.innerHeight - 150; drawMap(); }");
            sb.AppendLine("window.addEventListener('resize', resize);");
            sb.AppendLine("");
            sb.AppendLine("let centerX = 0, centerZ = 0, scale = 1;");
            sb.AppendLine("let dragStartX = 0, dragStartY = 0, dragStartCX = 0, dragStartCZ = 0, isDragging = false;");
            sb.AppendLine("");
            sb.AppendLine("function fitMap() {");
            sb.AppendLine("    if (trailPoints.length < 2) return;");
            sb.AppendLine("    let minX = Infinity, maxX = -Infinity, minZ = Infinity, maxZ = -Infinity;");
            sb.AppendLine("    for (const p of trailPoints) {");
            sb.AppendLine("        if (p.x < minX) minX = p.x; if (p.x > maxX) maxX = p.x;");
            sb.AppendLine("        if (p.z < minZ) minZ = p.z; if (p.z > maxZ) maxZ = p.z;");
            sb.AppendLine("    }");
            sb.AppendLine("    centerX = (minX + maxX) / 2;");
            sb.AppendLine("    centerZ = (minZ + maxZ) / 2;");
            sb.AppendLine("    const range = Math.max(maxX - minX, maxZ - minZ, 1);");
            sb.AppendLine("    scale = (Math.min(W, H) * 0.85) / (range * 1.15);");
            sb.AppendLine("}");
            sb.AppendLine("");
            sb.AppendLine("function worldToScreen(wx, wz) {");
            sb.AppendLine("    const dx = (wx - centerX) * scale;");
            sb.AppendLine("    const dz = (wz - centerZ) * scale;");
            sb.AppendLine("    return { x: W/2 + dx, y: H/2 - dz };");
            sb.AppendLine("}");
            sb.AppendLine("");
            sb.AppendLine("function getTrailColor(speed) {");
            sb.AppendLine("    const minS = meta.minSpeed || 0;");
            sb.AppendLine("    const maxS = meta.maxSpeed || 125;");
            sb.AppendLine("    const s = Math.max(minS, Math.min(maxS, speed));");
            sb.AppendLine("    const t = (s - minS) / (maxS - minS);");
            sb.AppendLine("    let r,g,b;");
            sb.AppendLine("    if (t <= 0.2) { const u = t/0.2; r=0; g=u*255; b=255; }");
            sb.AppendLine("    else if (t <= 0.4) { const u=(t-0.2)/0.2; r=0; g=255; b=255-u*255; }");
            sb.AppendLine("    else if (t <= 0.6) { const u=(t-0.4)/0.2; r=u*255; g=255; b=0; }");
            sb.AppendLine("    else if (t <= 0.8) { const u=(t-0.6)/0.2; r=255; g=255-u*(255-165); b=0; }");
            sb.AppendLine("    else { const u=(t-0.8)/0.2; r=255-u*(255-128); g=165-u*165; b=u*255; }");
            sb.AppendLine("    return `rgb(${Math.round(r)}, ${Math.round(g)}, ${Math.round(b)})`;");
            sb.AppendLine("}");
            sb.AppendLine("");
            sb.AppendLine("// ================================================================");
            sb.AppendLine("// ОТРИСОВКА КАРТЫ");
            sb.AppendLine("// ================================================================");
            sb.AppendLine("function drawMap() {");
            sb.AppendLine("    ctx.clearRect(0, 0, W, H);");
            sb.AppendLine("    ctx.fillStyle = '#0f1217'; ctx.fillRect(0, 0, W, H);");
            sb.AppendLine("    // Сетка");
            sb.AppendLine("    const gridStep = 200 / scale;");
            sb.AppendLine("    ctx.strokeStyle = '#2a3545'; ctx.lineWidth = 0.5; ctx.setLineDash([4,6]);");
            sb.AppendLine("    for (let x = -W/2; x < W/2; x += gridStep) { const p = worldToScreen(centerX+x, centerZ); ctx.beginPath(); ctx.moveTo(p.x,0); ctx.lineTo(p.x,H); ctx.stroke(); }");
            sb.AppendLine("    for (let z = -H/2; z < H/2; z += gridStep) { const p = worldToScreen(centerX, centerZ+z); ctx.beginPath(); ctx.moveTo(0,p.y); ctx.lineTo(W,p.y); ctx.stroke(); }");
            sb.AppendLine("    ctx.setLineDash([]);");
            sb.AppendLine("    // Дороги");
            sb.AppendLine("    for (const r of roads) {");
            sb.AppendLine("        const p1 = worldToScreen(r.x1, r.z1);");
            sb.AppendLine("        const p2 = worldToScreen(r.x2, r.z2);");
            sb.AppendLine("        ctx.beginPath(); ctx.moveTo(p1.x,p1.y); ctx.lineTo(p2.x,p2.y);");
            sb.AppendLine("        ctx.strokeStyle = '#5a7a8a'; ctx.lineWidth = 1.5; ctx.globalAlpha = 0.6; ctx.stroke();");
            sb.AppendLine("    }");
            sb.AppendLine("    ctx.globalAlpha = 1;");
            sb.AppendLine("    // Города");
            sb.AppendLine("    ctx.textAlign = 'center'; ctx.textBaseline = 'middle';");
            sb.AppendLine("    for (const c of cities) {");
            sb.AppendLine("        const p = worldToScreen(c.x, c.z);");
            sb.AppendLine("        if (p.x < 0 || p.x > W || p.y < 0 || p.y > H) continue;");
            sb.AppendLine("        ctx.beginPath(); ctx.arc(p.x, p.y, 4, 0, 2*Math.PI);");
            sb.AppendLine("        ctx.fillStyle = '#ffdd88'; ctx.shadowColor = '#ffdd8844'; ctx.shadowBlur = 6; ctx.fill(); ctx.shadowBlur = 0;");
            sb.AppendLine("        ctx.font = '10px \"Segoe UI\"'; ctx.fillStyle = '#c8ddee'; ctx.fillText(c.name, p.x, p.y-6);");
            sb.AppendLine("    }");
            sb.AppendLine("    // Шлейф");
            sb.AppendLine("    if (trailPoints.length > 1) {");
            sb.AppendLine("        for (let i=1; i<trailPoints.length; i++) {");
            sb.AppendLine("            const p1 = trailPoints[i-1]; const p2 = trailPoints[i];");
            sb.AppendLine("            const s1 = worldToScreen(p1.x, p1.z);");
            sb.AppendLine("            const s2 = worldToScreen(p2.x, p2.z);");
            sb.AppendLine("            const speed = p2.speed || 0;");
            sb.AppendLine("            ctx.beginPath(); ctx.moveTo(s1.x,s1.y); ctx.lineTo(s2.x,s2.y);");
            sb.AppendLine("            ctx.strokeStyle = getTrailColor(speed); ctx.lineWidth = 2.5; ctx.shadowColor='rgba(0,0,0,0.5)'; ctx.shadowBlur=4; ctx.stroke(); ctx.shadowBlur=0;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("    // События");
            sb.AppendLine("    for (const e of events) {");
            sb.AppendLine("        const p = worldToScreen(e.x, e.z); if (p.x<0||p.x>W||p.y<0||p.y>H) continue;");
            sb.AppendLine("        const size=10; ctx.save(); ctx.translate(p.x,p.y); ctx.shadowColor='rgba(0,0,0,0.5)'; ctx.shadowBlur=6;");
            sb.AppendLine("        ctx.beginPath(); ctx.arc(0,0,size,0,2*Math.PI); ctx.fillStyle=e.color||'#ffffff'; ctx.fill(); ctx.shadowBlur=0; ctx.strokeStyle='#fff'; ctx.lineWidth=1.5; ctx.stroke();");
            sb.AppendLine("        ctx.fillStyle='#fff'; ctx.font='bold 10px \"Segoe UI\"'; ctx.textAlign='center'; ctx.textBaseline='middle'; ctx.fillText(e.label||'?',0,-1);");
            sb.AppendLine("        if (e.subtext) { ctx.fillStyle='#fff'; ctx.shadowColor='rgba(0,0,0,0.8)'; ctx.shadowBlur=3; ctx.font='7px \"Segoe UI\"'; ctx.textBaseline='top'; ctx.fillText(e.subtext,0,size+2); ctx.shadowBlur=0; }");
            sb.AppendLine("        ctx.restore();");
            sb.AppendLine("    }");
            sb.AppendLine("    // Текущая позиция (с интерполяцией)");
            sb.AppendLine("    if (trailPoints.length > 0) {");
            sb.AppendLine("        let idx = currentIndex;");
            sb.AppendLine("        let nextIdx = Math.min(idx + 1, trailPoints.length - 1);");
            sb.AppendLine("        let p1 = trailPoints[idx];");
            sb.AppendLine("        let p2 = trailPoints[nextIdx];");
            sb.AppendLine("        let t1 = p1.t;");
            sb.AppendLine("        let t2 = p2.t;");
            sb.AppendLine("        let currentPos = { x: p1.x, z: p1.z, heading: p1.heading || 0, speed: p1.speed || 0 };");
            sb.AppendLine("        if (interpolate && idx < trailPoints.length - 1 && t2 > t1) {");
            sb.AppendLine("            const progress = (currentTime - t1) / (t2 - t1);");
            sb.AppendLine("            const clampedProgress = Math.max(0, Math.min(1, progress));");
            sb.AppendLine("            currentPos.x = p1.x + (p2.x - p1.x) * clampedProgress;");
            sb.AppendLine("            currentPos.z = p1.z + (p2.z - p1.z) * clampedProgress;");
            sb.AppendLine("            // Интерполяция heading с учётом перехода через 2π");
            sb.AppendLine("            let h1 = p1.heading || 0;");
            sb.AppendLine("            let h2 = p2.heading || 0;");
            sb.AppendLine("            let diff = h2 - h1;");
            sb.AppendLine("            while (diff > Math.PI) diff -= 2 * Math.PI;");
            sb.AppendLine("            while (diff < -Math.PI) diff += 2 * Math.PI;");
            sb.AppendLine("            currentPos.heading = h1 + diff * clampedProgress;");
            sb.AppendLine("            currentPos.speed = p1.speed + (p2.speed - p1.speed) * clampedProgress;");
            sb.AppendLine("        }");
            sb.AppendLine("        const sp = worldToScreen(currentPos.x, currentPos.z);");
            sb.AppendLine("        const heading = currentPos.heading || 0;");
            sb.AppendLine("        ctx.save(); ctx.translate(sp.x, sp.y);");
            sb.AppendLine("        ctx.rotate(heading + Math.PI);");
            sb.AppendLine("        ctx.beginPath(); ctx.moveTo(0, -14); ctx.lineTo(-9, 9); ctx.lineTo(0, 3); ctx.lineTo(9, 9); ctx.closePath();");
            sb.AppendLine("        ctx.fillStyle='#ff4d4d'; ctx.shadowColor='#ff4d4d88'; ctx.shadowBlur=12; ctx.fill(); ctx.shadowBlur=0; ctx.strokeStyle='#fff'; ctx.lineWidth=1.5; ctx.stroke();");
            sb.AppendLine("        ctx.restore();");
            sb.AppendLine("        // Скорость под грузовиком");
            sb.AppendLine("        ctx.save(); ctx.translate(sp.x, sp.y+22); ctx.font='10px \"Segoe UI\"'; ctx.fillStyle='#fff'; ctx.shadowColor='rgba(0,0,0,0.8)'; ctx.shadowBlur=4; ctx.textAlign='center'; ctx.textBaseline='top'; ctx.fillText(`${currentPos.speed.toFixed(0)} km/h`,0,0); ctx.restore();");
            sb.AppendLine("    }");
            sb.AppendLine("    // Данные (топливо, повреждения)");
            sb.AppendLine("    if (dataPoints.length > 0 && currentIndex < trailPoints.length) {");
            sb.AppendLine("        let closest = null; let minDist = Infinity;");
            sb.AppendLine("        const curP = trailPoints[currentIndex];");
            sb.AppendLine("        for (const dp of dataPoints) {");
            sb.AppendLine("            const d = Math.hypot(dp.x - curP.x, dp.z - curP.z);");
            sb.AppendLine("            if (d < minDist) { minDist = d; closest = dp; }");
            sb.AppendLine("        }");
            sb.AppendLine("        if (closest) {");
            sb.AppendLine("            document.getElementById('dataPanel').innerHTML = `⛽ ${closest.fuel.toFixed(1) || '--'} л &nbsp;|&nbsp; 🛠️ ${closest.damage.toFixed(1) || '--'}%`;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("    // Обновляем индикатор pitch/roll (умножаем на 1000 для наглядности)");
            sb.AppendLine("    if (closest && closest.pitch !== undefined && closest.roll !== undefined) {");
            sb.AppendLine("        const pitchVal = closest.pitch * 1000;");
            sb.AppendLine("        const rollVal = closest.roll * 1000;");
            sb.AppendLine("        document.getElementById('pitchFill').style.width = Math.min(100, Math.max(0, 50 + pitchVal * 5)) + '%';");
            sb.AppendLine("        document.getElementById('rollFill').style.width = Math.min(100, Math.max(0, 50 + rollVal * 5)) + '%';");
            sb.AppendLine("        document.getElementById('pitchLabel').textContent = pitchVal.toFixed(0);");
            sb.AppendLine("        document.getElementById('rollLabel').textContent = rollVal.toFixed(0);");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine("");
            sb.AppendLine("// ================================================================");
            sb.AppendLine("// УПРАВЛЕНИЕ КАРТОЙ");
            sb.AppendLine("// ================================================================");
            sb.AppendLine("canvas.addEventListener('wheel', (e) => {");
            sb.AppendLine("    e.preventDefault();");
            sb.AppendLine("    const delta = e.deltaY > 0 ? 0.9 : 1.1;");
            sb.AppendLine("    scale *= delta; if (scale < 0.001) scale = 0.001; if (scale > 1000) scale = 1000; drawMap();");
            sb.AppendLine("}, { passive: false });");
            sb.AppendLine("");
            sb.AppendLine("canvas.addEventListener('mousedown', (e) => {");
            sb.AppendLine("    if (e.button === 0) {");
            sb.AppendLine("        isDragging = true;");
            sb.AppendLine("        dragStartX = e.clientX; dragStartY = e.clientY;");
            sb.AppendLine("        dragStartCX = centerX; dragStartCZ = centerZ;");
            sb.AppendLine("        canvas.style.cursor = 'grabbing';");
            sb.AppendLine("    }");
            sb.AppendLine("});");
            sb.AppendLine("window.addEventListener('mousemove', (e) => {");
            sb.AppendLine("    if (isDragging) {");
            sb.AppendLine("        const dx = (e.clientX - dragStartX) / scale;");
            sb.AppendLine("        const dy = (dragStartY - e.clientY) / scale;");
            sb.AppendLine("        centerX = dragStartCX - dx;");
            sb.AppendLine("        centerZ = dragStartCZ - dy;");
            sb.AppendLine("        drawMap();");
            sb.AppendLine("    }");
            sb.AppendLine("    // Координаты под курсором");
            sb.AppendLine("    const rect = canvas.getBoundingClientRect();");
            sb.AppendLine("    const mx = e.clientX - rect.left;");
            sb.AppendLine("    const my = e.clientY - rect.top;");
            sb.AppendLine("    if (mx >= 0 && mx <= W && my >= 0 && my <= H) {");
            sb.AppendLine("        const wx = centerX + (mx - W/2) / scale;");
            sb.AppendLine("        const wz = centerZ - (my - H/2) / scale;");
            sb.AppendLine("        document.getElementById('cursorCoords').textContent = `📍 ${wx.toFixed(1)}, ${wz.toFixed(1)}`;");
            sb.AppendLine("    }");
            sb.AppendLine("});");
            sb.AppendLine("window.addEventListener('mouseup', () => { if (isDragging) { isDragging = false; canvas.style.cursor = 'grab'; } });");
            sb.AppendLine("");
            sb.AppendLine("// Клик для копирования координат и заметок");
            sb.AppendLine("let notes = [];");
            sb.AppendLine("canvas.addEventListener('click', (e) => {");
            sb.AppendLine("    const rect = canvas.getBoundingClientRect();");
            sb.AppendLine("    const mx = e.clientX - rect.left;");
            sb.AppendLine("    const my = e.clientY - rect.top;");
            sb.AppendLine("    if (mx < 0 || mx > W || my < 0 || my > H) return;");
            sb.AppendLine("    const wx = centerX + (mx - W/2) / scale;");
            sb.AppendLine("    const wz = centerZ - (my - H/2) / scale;");
            sb.AppendLine("    const coordStr = `${wx.toFixed(2)}, ${wz.toFixed(2)}`;");
            sb.AppendLine("    // Проверяем попадание в объекты");
            sb.AppendLine("    let objName = '';");
            sb.AppendLine("    for (const c of cities) {");
            sb.AppendLine("        const dx = c.x - wx; const dz = c.z - wz;");
            sb.AppendLine("        if (dx*dx + dz*dz < 100) { objName = c.name; break; }");
            sb.AppendLine("    }");
            sb.AppendLine("    if (!objName) {");
            sb.AppendLine("        for (const e of events) {");
            sb.AppendLine("            const dx = e.x - wx; const dz = e.z - wz;");
            sb.AppendLine("            if (dx*dx + dz*dz < 100) { objName = e.label || ''; break; }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("    const note = objName ? `${coordStr} – ${objName}` : coordStr;");
            sb.AppendLine("    notes.push(note);");
            sb.AppendLine("    navigator.clipboard?.writeText(coordStr);");
            sb.AppendLine("    // Показываем уведомление");
            sb.AppendLine("    const toast = document.createElement('div');");
            sb.AppendLine("    toast.style.cssText = 'position:fixed;bottom:170px;left:50%;transform:translateX(-50%);background:rgba(0,0,0,0.8);color:#fff;padding:4px 12px;border-radius:4px;font-size:12px;z-index:999;pointer-events:none;'");
            sb.AppendLine("    toast.textContent = `Скопировано: ${coordStr}`;");
            sb.AppendLine("    document.body.appendChild(toast);");
            sb.AppendLine("    setTimeout(() => toast.remove(), 2000);");
            sb.AppendLine("});");
            sb.AppendLine("");
            sb.AppendLine("// Измерение расстояния (двойной клик)");
            sb.AppendLine("let measureMode = false; let measureStart = null;");
            sb.AppendLine("canvas.addEventListener('dblclick', (e) => {");
            sb.AppendLine("    const rect = canvas.getBoundingClientRect();");
            sb.AppendLine("    const mx = e.clientX - rect.left;");
            sb.AppendLine("    const my = e.clientY - rect.top;");
            sb.AppendLine("    if (mx < 0 || mx > W || my < 0 || my > H) return;");
            sb.AppendLine("    const wx = centerX + (mx - W/2) / scale;");
            sb.AppendLine("    const wz = centerZ - (my - H/2) / scale;");
            sb.AppendLine("    if (!measureMode) {");
            sb.AppendLine("        measureMode = true;");
            sb.AppendLine("        measureStart = { x: wx, z: wz };");
            sb.AppendLine("        document.getElementById('measureTool').classList.add('active');");
            sb.AppendLine("        document.getElementById('measureDist').textContent = '0.0';");
            sb.AppendLine("        return;");
            sb.AppendLine("    }");
            sb.AppendLine("    const dx = wx - measureStart.x; const dz = wz - measureStart.z;");
            sb.AppendLine("    const dist = Math.sqrt(dx*dx + dz*dz);");
            sb.AppendLine("    document.getElementById('measureDist').textContent = dist.toFixed(1);");
            sb.AppendLine("    measureMode = false; measureStart = null;");
            sb.AppendLine("    setTimeout(() => document.getElementById('measureTool').classList.remove('active'), 5000);");
            sb.AppendLine("});");
            sb.AppendLine("");
            sb.AppendLine("// ================================================================");
            sb.AppendLine("// ТАЙМЛАЙН И ВОСПРОИЗВЕДЕНИЕ");
            sb.AppendLine("// ================================================================");
            sb.AppendLine("let playing = false;");
            sb.AppendLine("let speedFactor = 1;");
            sb.AppendLine("let currentIndex = 0;");
            sb.AppendLine("let follow = true;");
            sb.AppendLine("let interpolate = true;");
            sb.AppendLine("let playStartTime = 0;");
            sb.AppendLine("let playStartElapsed = 0;");
            sb.AppendLine("let currentTime = 0;");
            sb.AppendLine("");
            sb.AppendLine("const playBtn = document.getElementById('playBtn');");
            sb.AppendLine("const speedLabel = document.getElementById('speedLabel');");
            sb.AppendLine("const timeSlider = document.getElementById('timeSlider');");
            sb.AppendLine("const timeDisplay = document.getElementById('timeDisplay');");
            sb.AppendLine("const followCheck = document.getElementById('followCheck');");
            sb.AppendLine("const interpolateCheck = document.getElementById('interpolateCheck');");
            sb.AppendLine("const stepInput = document.getElementById('stepInput');");
            sb.AppendLine("const beginBtn = document.getElementById('beginBtn');");
            sb.AppendLine("const endBtn = document.getElementById('endBtn');");
            sb.AppendLine("const stepBackBtn = document.getElementById('stepBackBtn');");
            sb.AppendLine("const stepForwardBtn = document.getElementById('stepForwardBtn');");
            sb.AppendLine("const prevEventBtn = document.getElementById('prevEventBtn');");
            sb.AppendLine("const nextEventBtn = document.getElementById('nextEventBtn');");
            sb.AppendLine("");
            sb.AppendLine("function formatTime(seconds) {");
            sb.AppendLine("    const h = Math.floor(seconds / 3600);");
            sb.AppendLine("    const m = Math.floor((seconds % 3600) / 60);");
            sb.AppendLine("    const s = Math.floor(seconds % 60);");
            sb.AppendLine("    const ms = Math.floor((seconds - Math.floor(seconds)) * 1000);");
            sb.AppendLine("    return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(ms).padStart(3,'0')}`;");
            sb.AppendLine("}");
            sb.AppendLine("");
            sb.AppendLine("function updateTimeDisplay() {");
            sb.AppendLine("    const percent = totalDuration > 0 ? currentTime / totalDuration : 0;");
            sb.AppendLine("    timeSlider.value = percent * 1000;");
            sb.AppendLine("    timeDisplay.textContent = formatTime(currentTime);");
            sb.AppendLine("    drawMap();");
            sb.AppendLine("}");
            sb.AppendLine("");
            sb.AppendLine("function setTimeByValue(value) {");
            sb.AppendLine("    const target = value * totalDuration;");
            sb.AppendLine("    currentTime = Math.min(target, totalDuration);");
            sb.AppendLine("    // Находим индекс точки, ближайшей по времени");
            sb.AppendLine("    let idx = 0;");
            sb.AppendLine("    for (let i=0; i<times.length; i++) {");
            sb.AppendLine("        if (times[i] <= currentTime) idx = i; else break;");
            sb.AppendLine("    }");
            sb.AppendLine("    currentIndex = Math.min(idx, trailPoints.length-1);");
            sb.AppendLine("    if (follow) { const p = trailPoints[currentIndex]; centerX = p.x; centerZ = p.z; }");
            sb.AppendLine("    updateTimeDisplay();");
            sb.AppendLine("}");
            sb.AppendLine("");
            sb.AppendLine("function playStep() {");
            sb.AppendLine("    if (!playing) return;");
            sb.AppendLine("    const now = performance.now() / 1000;");
            sb.AppendLine("    const elapsed = (now - playStartTime) * speedFactor + playStartElapsed;");
            sb.AppendLine("    const progress = Math.min(elapsed / totalDuration, 1);");
            sb.AppendLine("    currentTime = Math.min(elapsed, totalDuration);");
            sb.AppendLine("    // Находим индекс точки, ближайшей по времени");
            sb.AppendLine("    let idx = 0;");
            sb.AppendLine("    for (let i=0; i<times.length; i++) {");
            sb.AppendLine("        if (times[i] <= currentTime) idx = i; else break;");
            sb.AppendLine("    }");
            sb.AppendLine("    currentIndex = Math.min(idx, trailPoints.length-1);");
            sb.AppendLine("    if (follow) { const p = trailPoints[currentIndex]; centerX = p.x; centerZ = p.z; }");
            sb.AppendLine("    updateTimeDisplay();");
            sb.AppendLine("    if (currentTime >= totalDuration) {");
            sb.AppendLine("        playing = false;");
            sb.AppendLine("        playBtn.textContent = '▶';");
            sb.AppendLine("        return;");
            sb.AppendLine("    }");
            sb.AppendLine("    requestAnimationFrame(playStep);");
            sb.AppendLine("}");
            sb.AppendLine("");
            sb.AppendLine("// Управление");
            sb.AppendLine("playBtn.addEventListener('click', () => {");
            sb.AppendLine("    playing = !playing;");
            sb.AppendLine("    playBtn.textContent = playing ? '⏸' : '▶';");
            sb.AppendLine("    if (playing) {");
            sb.AppendLine("        if (currentTime >= totalDuration) { currentTime = 0; currentIndex = 0; if (follow) { const p = trailPoints[0]; centerX=p.x; centerZ=p.z; } }");
            sb.AppendLine("        playStartTime = performance.now() / 1000;");
            sb.AppendLine("        playStartElapsed = currentTime;");
            sb.AppendLine("        playStep();");
            sb.AppendLine("    }");
            sb.AppendLine("});");
            sb.AppendLine("");
            sb.AppendLine("beginBtn.addEventListener('click', () => {");
            sb.AppendLine("    if (playing) { playing = false; playBtn.textContent = '▶'; }");
            sb.AppendLine("    currentTime = 0; currentIndex = 0;");
            sb.AppendLine("    if (follow) { const p = trailPoints[0]; centerX = p.x; centerZ = p.z; }");
            sb.AppendLine("    updateTimeDisplay();");
            sb.AppendLine("});");
            sb.AppendLine("");
            sb.AppendLine("endBtn.addEventListener('click', () => {");
            sb.AppendLine("    if (playing) { playing = false; playBtn.textContent = '▶'; }");
            sb.AppendLine("    currentTime = totalDuration; currentIndex = trailPoints.length-1;");
            sb.AppendLine("    if (follow) { const p = trailPoints[currentIndex]; centerX = p.x; centerZ = p.z; }");
            sb.AppendLine("    updateTimeDisplay();");
            sb.AppendLine("});");
            sb.AppendLine("");
            sb.AppendLine("stepBackBtn.addEventListener('click', () => {");
            sb.AppendLine("    if (playing) { playing = false; playBtn.textContent = '▶'; }");
            sb.AppendLine("    const step = parseFloat(stepInput.value) || 1;");
            sb.AppendLine("    let targetTime = currentTime - step;");
            sb.AppendLine("    if (targetTime < 0) targetTime = 0;");
            sb.AppendLine("    currentTime = targetTime;");
            sb.AppendLine("    let idx = 0;");
            sb.AppendLine("    for (let i=0; i<times.length; i++) {");
            sb.AppendLine("        if (times[i] <= currentTime) idx = i; else break;");
            sb.AppendLine("    }");
            sb.AppendLine("    currentIndex = Math.min(idx, trailPoints.length-1);");
            sb.AppendLine("    if (follow) { const p = trailPoints[currentIndex]; centerX = p.x; centerZ = p.z; }");
            sb.AppendLine("    updateTimeDisplay();");
            sb.AppendLine("});");
            sb.AppendLine("");
            sb.AppendLine("stepForwardBtn.addEventListener('click', () => {");
            sb.AppendLine("    if (playing) { playing = false; playBtn.textContent = '▶'; }");
            sb.AppendLine("    const step = parseFloat(stepInput.value) || 1;");
            sb.AppendLine("    let targetTime = currentTime + step;");
            sb.AppendLine("    if (targetTime > totalDuration) targetTime = totalDuration;");
            sb.AppendLine("    currentTime = targetTime;");
            sb.AppendLine("    let idx = 0;");
            sb.AppendLine("    for (let i=0; i<times.length; i++) {");
            sb.AppendLine("        if (times[i] <= currentTime) idx = i; else break;");
            sb.AppendLine("    }");
            sb.AppendLine("    currentIndex = Math.min(idx, trailPoints.length-1);");
            sb.AppendLine("    if (follow) { const p = trailPoints[currentIndex]; centerX = p.x; centerZ = p.z; }");
            sb.AppendLine("    updateTimeDisplay();");
            sb.AppendLine("});");
            sb.AppendLine("");
            sb.AppendLine("prevEventBtn.addEventListener('click', () => {");
            sb.AppendLine("    if (playing) { playing = false; playBtn.textContent = '▶'; }");
            sb.AppendLine("    const currentT = currentTime;");
            sb.AppendLine("    let prevEvent = null;");
            sb.AppendLine("    for (const e of events) {");
            sb.AppendLine("        if (e.t < currentT) { prevEvent = e; } else break;");
            sb.AppendLine("    }");
            sb.AppendLine("    if (prevEvent) {");
            sb.AppendLine("        currentTime = prevEvent.t;");
            sb.AppendLine("        let idx = 0;");
            sb.AppendLine("        for (let i=0; i<times.length; i++) {");
            sb.AppendLine("            if (times[i] <= currentTime) idx = i; else break;");
            sb.AppendLine("        }");
            sb.AppendLine("        currentIndex = Math.min(idx, trailPoints.length-1);");
            sb.AppendLine("        if (follow) { const p = trailPoints[currentIndex]; centerX = p.x; centerZ = p.z; }");
            sb.AppendLine("        updateTimeDisplay();");
            sb.AppendLine("    }");
            sb.AppendLine("});");
            sb.AppendLine("");
            sb.AppendLine("nextEventBtn.addEventListener('click', () => {");
            sb.AppendLine("    if (playing) { playing = false; playBtn.textContent = '▶'; }");
            sb.AppendLine("    const currentT = currentTime;");
            sb.AppendLine("    let nextEvent = null;");
            sb.AppendLine("    for (const e of events) {");
            sb.AppendLine("        if (e.t > currentT) { nextEvent = e; break; }");
            sb.AppendLine("    }");
            sb.AppendLine("    if (nextEvent) {");
            sb.AppendLine("        currentTime = nextEvent.t;");
            sb.AppendLine("        let idx = 0;");
            sb.AppendLine("        for (let i=0; i<times.length; i++) {");
            sb.AppendLine("            if (times[i] <= currentTime) idx = i; else break;");
            sb.AppendLine("        }");
            sb.AppendLine("        currentIndex = Math.min(idx, trailPoints.length-1);");
            sb.AppendLine("        if (follow) { const p = trailPoints[currentIndex]; centerX = p.x; centerZ = p.z; }");
            sb.AppendLine("        updateTimeDisplay();");
            sb.AppendLine("    }");
            sb.AppendLine("});");
            sb.AppendLine("");
            sb.AppendLine("speedDownBtn.addEventListener('click', () => { speedFactor = Math.max(0.5, speedFactor/1.5); speedLabel.textContent = speedFactor.toFixed(1)+'×'; });");
            sb.AppendLine("speedUpBtn.addEventListener('click', () => { speedFactor = Math.min(5, speedFactor*1.5); speedLabel.textContent = speedFactor.toFixed(1)+'×'; });");
            sb.AppendLine("");
            sb.AppendLine("timeSlider.addEventListener('input', () => {");
            sb.AppendLine("    if (playing) { playing = false; playBtn.textContent = '▶'; }");
            sb.AppendLine("    const val = parseFloat(timeSlider.value) / 1000;");
            sb.AppendLine("    setTimeByValue(val);");
            sb.AppendLine("});");
            sb.AppendLine("");
            sb.AppendLine("followCheck.addEventListener('change', () => { follow = followCheck.checked; if (follow && currentIndex < trailPoints.length) { const p = trailPoints[currentIndex]; centerX=p.x; centerZ=p.z; drawMap(); } });");
            sb.AppendLine("interpolateCheck.addEventListener('change', () => { interpolate = interpolateCheck.checked; drawMap(); });");
            sb.AppendLine("");
            sb.AppendLine("// Инициализация");
            sb.AppendLine("resize(); fitMap();");
            sb.AppendLine("if (trailPoints.length > 0) { currentTime = 0; currentIndex = 0; const p = trailPoints[0]; centerX=p.x; centerZ=p.z; }");
            sb.AppendLine("drawMap(); updateTimeDisplay();");
            sb.AppendLine("window.addEventListener('resize', () => { resize(); fitMap(); drawMap(); });");
            sb.AppendLine("</script>");
            sb.AppendLine("</body>");
            sb.AppendLine("</html>");
            return sb.ToString();
        }

        private string GenerateTrailPlayerHtml()
        {
            return @"<!DOCTYPE html>
<html>
<head>
<meta charset=""utf-8""/>
<title>ETS2 Trail Player</title>
<style>
    body { background:#0a0c10; color:#e0e0e0; font-family:'Segoe UI',sans-serif; margin:20px; }
    #trackList { display:flex; flex-direction:column; gap:6px; max-width:500px; margin:20px auto; }
    .track-item { background:#1a1f26; padding:10px 16px; border:1px solid #333; border-radius:6px; cursor:pointer; transition:0.2s; }
    .track-item:hover { background:#2a3545; }
    #playerContainer { margin-top:20px; }
    iframe { width:100%; height:600px; border:none; background:#111; border-radius:8px; }
</style>
</head>
<body>
<h1 style=""text-align:center;"">ETS2 Trail Player</h1>
<div id=""trackList"">Загрузка...</div>
<div id=""playerContainer""></div>
<script>
async function loadTracks() {
    try {
        const res = await fetch('http://localhost:8083/list_tracks');
        const data = await res.json();
        const list = document.getElementById('trackList');
        list.innerHTML = '';
        if (data.files.length === 0) {
            list.innerHTML = '<div style=""color:#666;"">Нет сохранённых треков</div>';
            return;
        }
        for (const file of data.files) {
            const div = document.createElement('div');
            div.className = 'track-item';
            const name = file.replace('.json', '');
            div.textContent = name;
            div.addEventListener('click', () => {
                const container = document.getElementById('playerContainer');
                container.innerHTML = `<iframe src=""http://localhost:8082/saved_tracks/${name}.html""></iframe>`;
            });
            list.appendChild(div);
        }
    } catch (e) {
        document.getElementById('trackList').innerHTML = 'Ошибка загрузки списка: ' + e.message;
    }
}
loadTracks();
</script>
</body>
</html>";
        }
    }
}